# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    paths:
      - '**.py'
      - "python-test-samples/**"
permissions:
  contents: read
defaults:
  run:
    working-directory: python-test-samples
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Stockopedia/action-get-changed-files@v1
      id: get_changed
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        ignore: "**/+(.github)"
        foldersOnly: false
        format: newline
    - name: Echo changed files
      run: |
        file=${{ steps.get_changed.outputs.changed }}
        echo $file
        folder=$file | awk -F'/' '{print $2}'
        echo $folder
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd apigw-lambda-dynamodb
        python -m pip install --upgrade pip
        pip install flake8 pytest boto3
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
    - name: Lint with flake8
      run: |
        cd apigw-lambda-dynamodb
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pwd
        cd apigw-lambda-dynamodb
        pytest -s tests/unit  -v